apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-alpine
  namespace: default
  labels:
    app: nginx-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-alpine
  template:
    metadata:
      labels:
        app: nginx-alpine
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80